from app.models.user import User
from app.models.institution import Institution
from app.models.class_model import Class
from app.models.student import Student
from app.models.department import Department
from app.models.employee import Employee
from app.models.parent import Parent
from app.models.student_parent import StudentParent
from app.models.attendance import Attendance
from app.models.leave_application import LeaveApplication
from app.models.task import Task
from app.models.principal import Principal
from app.models.schedule import ScheduleEntry
from app.models.certificate import Certificate
from app.models.library_book import LibraryBook
from app.models.library_transaction import LibraryTransaction
from app.models.substitution import Substitution
from app.models.teacher import Teacher
from app.models.teacher_subject import TeacherSubject
from app.models.subject import Subject
from app.models.room import Room
from app.models.period import Period
